# Generated by Django 5.2.12 on 2026-03-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_gratifikasirecord_ai_result_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratifikasirecord',
            name='context',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gratifikasirecord',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gratifikasirecord',
            name='regulatory_framework',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gratifikasirecord',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
